name: Docker

on:
  push:
    branches:
      - master
      - github-actions
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Image Tag'
        required: true

jobs:
  build-test-publish:
    name: Build, Test, Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:
          - centos-7
          - bionic

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Login to ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.CR_USERNAME }}
        password: ${{ secrets.CR_PAT }}

    - name: Build
      uses: docker/build-push-action@v2
      with:
        file: ${{ matrix.distro }}/Dockerfile
        context: .
        push: true
        tags: ghcr.io/nervosnetwork/ckb-docker-builder:${{ matrix.distro }}-${{ github.sha }}

    - name: Checkout CKB
      uses: actions/checkout@v2
      with:
        repository: nervosnetwork/ckb
        path: ckb

    - name: Build CKB
      run: |
        docker run --rm -i -w /ckb -v $(pwd)/ckb:/ckb nervos/ckb-docker-builder:${{ matrix.distro }}-${{ github.sha }} make prod

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag and push image
      if: ${{ github.event.inputs.tag != '' }}
      uses: akhilerm/tag-push-action@v1.0.0
      with:
        src: ghcr.io/nervosnetwork/ckb-docker-builder:${{ matrix.distro }}-${{ github.sha }}
        dst: |
          ghcr.io/nervosnetwork/ckb-docker-builder:${{ matrix.distro }}-latest
          ghcr.io/nervosnetwork/ckb-docker-builder:${{ matrix.distro }}-${{ github.event.inputs.tag }}
          nervos/ckb-docker-builder:${{ matrix.distro }}-latest
          nervos/ckb-docker-builder:${{ matrix.distro }}-${{ github.event.inputs.tag }}
